### ISSUE TITLE
Mise à jour de certains exemples

### ISSUE THREAD

**Issue by ebachard** [jjfPCSI1/py4phys#3]
Bonjour Jean-Julien,

J'ai un peu testé les exemples et comme ça ne fonctionnait pas sur ma machine, j'ai modifié ce qu'il fallait pour quelques exemples. Par exemple celui-ci.

Cependant, cela ne sert pas à grand chose de corriger 1 seul exemple, et c'est la raison pour laquelle je n'ai pas fait de pull request.

Les corrections sont là:

- https://github.com/ebachard/py4phys/commit/91fc0566883d3db63f291de3788bdd97fb9c71b1

- https://github.com/ebachard/py4phys/commit/fdd18767b1b6d1a0d5774b3a81d4b316ac75a7a9

Si tu es intéressé, dis le moi. J'ai quelques jours de vacances en ce moment : j'essayerai de corriger d'autres exemples et de faire la migration complète pour Qt5. Autre possibilité : ajouter de nouveaux exemples, en les renommant avec Qt4 ou Qt5 dans le nom, et proposer les 2. Avantage : chacun utilise ce qui fonctionne. Inconvénient : duplication de code.

Merci et surtout continue ton super boulot, c'est génial !

Eric

**Comment by jjfPCSI1** [comment]
Hello Eric,

Ce sera avec plaisir. 
Ce n'est pas du tout moi qui ait joué avec Qt donc je te laisse juge de ce qu'il faudrait changer.
C'est vrai que la duplication du code n'est pas top, mais si cela peut continuer à marcher pour les collègue qui ont d'anciennes versions, je préfère autant.

Merci pour ton aide !

**Comment by ebachard** [comment]
Franchement, ce que j'ai fait n'est pas grand chose. J'ai surtout pris plaisir à jouer avec tous les exemples, et c'est génial de pouvoir illustrer des notions avec ça !

En ce qui concerne la mise à jour Qt4 ->Qt5, tu as raison, seuls les exemples de chimie étaient concernés. Je ne suis pas chimiste, :-) mais j'ai fait ça de bon coeur, et j'ai appris des choses au passage.

Normalement, j'ai terminé pour ce qui ne se lançait pas. Avant de tout changer, il faudrait que quelqu'un teste les anciennes versions (pour vérifier que je n'ai rien cassé). Tout est là : https://github.com/ebachard/py4phys

Il suffit de faire un clone du dépôt et de tester. Quand j'aurai la confirmation que ça fonctionne ET si tu es d'accord, je ferai un PR. Encore merci pour ce travail énorme, et passionnant !

Eric

**Comment by jjfPCSI1** [comment]
Alors voici les remarques:
* le fichier `Chimie_optimisation_NH3_v2_Qt4.py` est identique à `Chimie_optimisation_NH3_v2_Qt5.py`, tu as dû faire une erreur de manip
* J'ai une erreur `ModuleNotFoundError: No module named 'matplotlib.backends.backend_qt4agg'` sur mon dernier Python et quand j'utilise celui d'avant j'ai un avertissement: `The support for Qt4  was deprecated in Matplotlib 3.3 and will be removed two minor releases later.` qui me semble vouloir dire qu'il va de toutes façon falloir laisser tomber Qt4. Qu'en penses-tu ? 
* Il faut aussi corriger tes fichier Qt5 car ils appellent justement `qt4agg`. Quand je remplace par `qt5agg`, ça marche mieux
* Enfin, penser à changer les docstring pour faire disparaître toutes mentions de Qt4 au profit de Qt5

Bref, mieux vaut passer entièrement à Qt5. Si jamais quelqu'un veut une version en Qt4, il n'y aura qu'à chercher dans l'historique des commits.

**Comment by ebachard** [comment]
Merci pour ton retour, c'est super utilie que tu utilises un autre OS que moi. Dans l'ordre:

- Ouch, j'étais mal réveillé :-) 
- Tu as raison, et j'ai changé qt4agg pour qt5agg partout où je l'ai trouvé.
- Je suis d'accord pour passer à qt5 (c'est la base partout amha).

En résumé :
- j'ai fait tout ce que tu m'as suggéré ;
- +j'ai fait le test le plus simple possible dans le répertoire lib: 

````
for i in Chimie_*.py ; do python3 ${i} ; done
````
=> les 4 fichiers s'exécutent, après chaque fermeture de la fenêtre précédente,et je n'ai pas de warning, ni d'erreur.

**Dès que tu confirmes que c'est OK, je propose une PR**

Suggestion : entre temps, j'ai fait un essai plus poussé, et je crois que les valeurs par défaut dans Chimie_optimisation_NH3_v2.py sont trop importantes, car de 0,001 à 1000 par par de 0,001 ça me semble donner beaucoup d'itérations par défaut. Après avoir killé la fenêtre qui ne répondait plus, en allant de 0,01 à 100 par pas de 0,01, ça me semble fonctionner mieux, et on peut cerner le domaine pour les paramètres où il se passe quelque chose d'intéressant. Mais je préfère te demander, je n'ai pas plus testé que ça.

**Comment by jjfPCSI1** [comment]
C'est bon chez moi.

Pour les paramètre, effectivement, 
* pour `Chimie_optimisation_NH3_v2.py` je propose d'aller de 0,001 à 10, ça permet de voir ce qui se passe au début
* pour `Chimie_optimisation_HI.py`, pareil, aller de 0,001 à 10 permet de mieux voir ce qui se passe tout en demandant bien moins de ressources.

**Comment by ebachard** [comment]
OK pour moi aussi: les modifications sont faites.

J'avais aussi trouvé que 10.0 donnait de bons résultats. 100.0 fonctionnait correctement aussi, mais me semblait élevé. De toutes façons, celui qui utilise le logiciel saura changer la valeur en cas de besoin particulier ;-)

**Comment by jjfPCSI1** [comment]
Tout à fait. Du coup, tu peux faire la PR je pense.
